// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearHistory():Promise<void>;

export function CreateProject(arg1:main.Project):Promise<void>;

export function DeleteEnvironment(arg1:string):Promise<void>;

export function DeleteHeader(arg1:string):Promise<void>;

export function DeleteHistoryRecord(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function ExchangeOAuth2Code(arg1:main.Auth,arg2:string):Promise<main.Auth>;

export function ExportAllData():Promise<string>;

export function ExportProjectAPI(arg1:string):Promise<void>;

export function GetActiveEnvironment():Promise<string>;

export function GetAllEnvironments():Promise<Array<main.Environment>>;

export function GetAllHeaders():Promise<Array<main.Header>>;

export function GetAllProjects():Promise<Array<main.Project>>;

export function GetEnvironment(arg1:string):Promise<main.Environment>;

export function GetHeader(arg1:string):Promise<main.Header>;

export function GetHistory(arg1:number):Promise<Array<main.HistoryRecord>>;

export function GetOAuth2ClientCredentialsToken(arg1:main.Auth):Promise<main.Auth>;

export function GetOAuth2PasswordToken(arg1:main.Auth,arg2:string,arg3:string):Promise<main.Auth>;

export function GetProject(arg1:string):Promise<main.Project>;

export function GetProjectRequests(arg1:string):Promise<Array<main.HistoryRecord>>;

export function GetSavedTabs():Promise<Array<main.TabState>>;

export function ImportAllData():Promise<string>;

export function ImportOpenAPI(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<main.HttpRequest>>;

export function ImportProjectAPI(arg1:string):Promise<void>;

export function ImportProjectJSON(arg1:string,arg2:string):Promise<void>;

export function RefreshOAuth2Token(arg1:main.Auth):Promise<main.Auth>;

export function ReplaceVariables(arg1:string):Promise<string>;

export function RunCollection(arg1:string):Promise<main.CollectionRunResult>;

export function SaveEnvironment(arg1:main.Environment):Promise<void>;

export function SaveHeader(arg1:main.Header):Promise<void>;

export function SaveTabsState(arg1:Array<main.TabState>):Promise<void>;

export function SearchHistory(arg1:string):Promise<Array<main.HistoryRecord>>;

export function SelectFile():Promise<string>;

export function SendRequest(arg1:main.HttpRequest):Promise<main.HttpResponse>;

export function SetActiveEnvironment(arg1:string):Promise<void>;

export function StartOAuth2Flow(arg1:main.Auth):Promise<void>;

export function UpdateProject(arg1:main.Project):Promise<void>;
