// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteEnvironment(arg1) {
  return window['go']['main']['App']['DeleteEnvironment'](arg1);
}

export function DeleteHeader(arg1) {
  return window['go']['main']['App']['DeleteHeader'](arg1);
}

export function DeleteHistoryRecord(arg1) {
  return window['go']['main']['App']['DeleteHistoryRecord'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function ExchangeOAuth2Code(arg1, arg2) {
  return window['go']['main']['App']['ExchangeOAuth2Code'](arg1, arg2);
}

export function ExportAllData() {
  return window['go']['main']['App']['ExportAllData']();
}

export function ExportProjectAPI(arg1) {
  return window['go']['main']['App']['ExportProjectAPI'](arg1);
}

export function GetActiveEnvironment() {
  return window['go']['main']['App']['GetActiveEnvironment']();
}

export function GetAllEnvironments() {
  return window['go']['main']['App']['GetAllEnvironments']();
}

export function GetAllHeaders() {
  return window['go']['main']['App']['GetAllHeaders']();
}

export function GetAllProjects() {
  return window['go']['main']['App']['GetAllProjects']();
}

export function GetEnvironment(arg1) {
  return window['go']['main']['App']['GetEnvironment'](arg1);
}

export function GetHeader(arg1) {
  return window['go']['main']['App']['GetHeader'](arg1);
}

export function GetHistory(arg1) {
  return window['go']['main']['App']['GetHistory'](arg1);
}

export function GetOAuth2ClientCredentialsToken(arg1) {
  return window['go']['main']['App']['GetOAuth2ClientCredentialsToken'](arg1);
}

export function GetOAuth2PasswordToken(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetOAuth2PasswordToken'](arg1, arg2, arg3);
}

export function GetProject(arg1) {
  return window['go']['main']['App']['GetProject'](arg1);
}

export function GetProjectRequests(arg1) {
  return window['go']['main']['App']['GetProjectRequests'](arg1);
}

export function GetSavedTabs() {
  return window['go']['main']['App']['GetSavedTabs']();
}

export function ImportAllData() {
  return window['go']['main']['App']['ImportAllData']();
}

export function ImportOpenAPI(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ImportOpenAPI'](arg1, arg2, arg3, arg4);
}

export function ImportProjectAPI(arg1) {
  return window['go']['main']['App']['ImportProjectAPI'](arg1);
}

export function ImportProjectJSON(arg1, arg2) {
  return window['go']['main']['App']['ImportProjectJSON'](arg1, arg2);
}

export function RefreshOAuth2Token(arg1) {
  return window['go']['main']['App']['RefreshOAuth2Token'](arg1);
}

export function ReplaceVariables(arg1) {
  return window['go']['main']['App']['ReplaceVariables'](arg1);
}

export function RunCollection(arg1) {
  return window['go']['main']['App']['RunCollection'](arg1);
}

export function SaveEnvironment(arg1) {
  return window['go']['main']['App']['SaveEnvironment'](arg1);
}

export function SaveHeader(arg1) {
  return window['go']['main']['App']['SaveHeader'](arg1);
}

export function SaveTabsState(arg1) {
  return window['go']['main']['App']['SaveTabsState'](arg1);
}

export function SearchHistory(arg1) {
  return window['go']['main']['App']['SearchHistory'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SendRequest(arg1) {
  return window['go']['main']['App']['SendRequest'](arg1);
}

export function SetActiveEnvironment(arg1) {
  return window['go']['main']['App']['SetActiveEnvironment'](arg1);
}

export function StartOAuth2Flow(arg1) {
  return window['go']['main']['App']['StartOAuth2Flow'](arg1);
}

export function UpdateProject(arg1) {
  return window['go']['main']['App']['UpdateProject'](arg1);
}
